name: fedora-copr-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install copr-cli
      run: | 
        sudo pip install copr-cli configparser
        copr-cli --version
    - name: Verify build status
      run: |
        while : ; do
          sleep 300
          BUILD_STATUS=$(copr-cli list-builds wereturtle/staging | head -1 | awk -F ' '  '{ print $(NF)}')
          [[ "$BUILD_STATUS" == "pending" ]] || [[ "$BUILD_STATUS" == "running" ]] || [[ "$BUILD_STATUS" == "waiting" ]] || [[ "$BUILD_STATUS" == "starting" ]] || break
        done
        echo "Copr build status = $BUILD_STATUS"
        if [[ "$BUILD_STATUS" == "failed" ]]; then exit 1; fi
